FROM resin/raspberrypi3-debian:latest


ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq \
  python3 \
  python3-sense-hat \
  wget && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY . ./

CMD ["python3", "app.py"]
