version: '2'
services:
  SimonSaysClient:
    build: ./SimonSaysClient
    privileged: true
  SimonSaysServer:
    build: ./SimonSaysServer
    privileged: true
  Broker:
    build: ./Broker
    privileged: true
network_mode: "host"
