FROM resin/raspberrypi3-debian:latest

ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq \
  python3 \
  python3-pip \
  python3-sense-hat \
  docker \
  wget && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install paho-mqtt

WORKDIR /usr/src/app
COPY ./app /usr/src/app

CMD ["python3", "/usr/src/app/app.py"]
