FROM resin/raspberrypi3-debian:latest

ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq \
  python3 \
  python3-pip \
  mosquitto \
  wget && \
  apt-get clean && rm -rf /var/lib/apt/lists/*


